name: AndroidBuild

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
            persist-credentials: false
            repository: ShineThyuZan/VideoPreCaching
            ref: develop
            lfs: true
            token: ${{ secrets.VIDEOPRECACHING }}  # Replace 'MY_PAT' with your secret name

      - name: Set Up JDK
        uses: actions/setup-java@v3

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0

        with:
          java-version: '18'
          distribution: 'adopt'


      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
