name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
            persist-credentials: false
            repository: ShineThyuZan/VideoPreCaching
            ref: develop
            lfs: true
            token: ${{ secrets.VIDEOPRECACHING }}  # Replace 'MY_PAT' with your secret name

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble
